### ISSUE TITLE
Cannot add azure-batch plugin after moving plugin location on disk

### ISSUE THREAD

**Issue by davidkydd** [Azure/azure-batch-maya#7]
Repro:
Moving the on-disk location of the azure-batch-maya repo after installing the plugin in maya.

Symptoms:
Attempting to install the plugin shows the following in the MEL window:
mayapy: can't open file 'D:\publicrepos\azure-batch-maya\azure_batch_maya\scripts\tools\install_pip.py': [Errno 2] No such file or directory
Failed to install Pip. Please install dependencies manually to continue.

(where "D:\publicrepos\azure-batch-maya\" was the old on-disk location)

Part solution:
Need to delete the AzureBatch.mod file which may be located in any of the folders specified by os.environ["MAYA_MODULE_PATH"], for me these were:

D:/Autodesk/Maya2017/modules;C:/Users/dakydd/Documents/maya/2017/modules;C:/Users/dakydd/Documents/maya/modules;C:/Program Files/Common Files/Autodesk Shared/Modules/maya/2017 

This allowed the plugin to at least find 'azure_batch_maya\scripts\tools\install_pip.py' and attempt to install the dependencies. 

Current problem:
Dependencies are not being detected as being installed by the plugin, which will attempt and fail to reinstall the dependencies when the plugin is re-loaded despite them already existing in the target install location of "C:\Users\dakydd\Documents\maya\2017\scripts\azure-batch-lib:"

e.g. console output:
Initializing Azure Batch plug-in
Checking for dependencies...
Unable to load azure-mgmt-batch==4.0.0
Unable to load azure-mgmt-storage==1.0.0
Unable to load azure-common==1.1.5
Unable to load azure-batch==3.0.0
Unable to load azure-storage==0.32.0
Attempting to install dependencies via Pip.
Installing dependencies
['mayapy', u'C:\\Users\\dakydd\\Documents\\maya\\2017\\scripts\\azure-batch-libs\\pip', 'install', 'azure-mgmt-batch==4.0.0', '--target', u'C:\\Users\\dakydd\\Documents\\maya\\2017\\scripts\\azure-batch-libs', '--index-url', 'http://pypi.python.org/simple/', '--trusted-host', 'pypi.python.org']
[Error 183] Cannot create a file when that file already exists: u'C:\\Users\\dakydd\\Documents\\maya\\2017\\scripts\\azure-batch-libs\\azure\\mgmt\\batch'
['mayapy', u'C:\\Users\\dakydd\\Documents\\maya\\2017\\scripts\\azure-batch-libs\\pip', 'install', 'azure-mgmt-storage==1.0.0', '--target', u'C:\\Users\\dakydd\\Documents\\maya\\2017\\scripts\\azure-batch-libs', '--index-url', 'http://pypi.python.org/simple/', '--trusted-host', 'pypi.python.org']
// Error: file: D:/Autodesk/Maya2017/scripts/others/pluginWin.mel line 820: ImportError: file D:/Git/Github/azure-batch-maya/azure_batch_maya/plug-in/AzureBatch.py line 455: Failed to install dependencies - please install manually //

**Comment by annatisch** [comment]
Thanks @davidkydd,
I'm curious about the trailing ':' in the scripts directory path - is that a typo or did you copy that from somewhere?
"C:\Users\dakydd\Documents\maya\2017\scripts\azure-batch-lib:"

This could indicate that the Python search path has not been updated correctly. Could you open Maya, attempt to load the plugin, and then once it has failed to load the dependencies, in the Python prompt/script editor print out the result of:
`import sys; print(sys.path)`

In this list of paths you should see the lib path:
"C:\Users\dakydd\Documents\maya\2017\scripts\azure-batch-libs"

If not, could you please post the list of paths?
This adding the script install path is the very first thing that the plugin does:
https://github.com/Azure/azure-batch-maya/blob/master/azure_batch_maya/plug-in/AzureBatch.py#L30
So it could also be worth confirming that `cmds.internalVar(userScriptDir=True)` resolves to the same directory that the packages have been installed to.

Assuming that all these paths look correct, the problem must be that the packages actually haven't been installed correctly. It seems to be telling that all the 'failed' dependencies are azure packages which we actually have to use a weird install process for because of a bug in the packaging. Can you confirm if you get the exact same error when you try to run using the vray branch?
I'm looking at the --target parameter and I don't think that's right - we should be installing to a temp location (azure-batch-libs/temp-target) and we then move the package into it's correct directory.

In azure-batch-libs you should see:
azure \
 - common
 - batch
 - batch_extensions
 - storage
 - mgmt \
      - batch
      - storage

**Comment by davidkydd** [comment]
_I'm curious about the trailing ':' in the scripts directory _path.._
Sorry - this was a typo

_In this list of paths you should see the lib path:
 "C:\Users\dakydd\Documents\maya\2017\scripts\azure-batch-libs"_
Yes it is present

_worth confirming that  cmds.internalVar(userScriptDir=True)  resolves to the same directory that the packages have been installed to._
'''
from maya import cmds
print cmds.internalVar(userScriptDir=True) 
'''
C:/Users/dakydd/Documents/maya/2017/scripts/

_Can you confirm if you get the exact same error when you try to run using the vray branch?_
Yes, confirm I get the same error from vray branch

_In azure-batch-libs you should see:
 azure \
•common
•batch
•batch_extensions
•storage
•mgmt \ ◦batch
◦storage_
These are all present

**Comment by davidkydd** [comment]
Found various env vars (MAYA_SCRIPT_PATH, MAYA_PLUGINS_PATH etc) pointing to vray script folders, removing these then reinstalling maya resolved the problem
